#include <signal.h>
#include <unistd.h>
#include <readline/readline.h>
#include <readline/history.h>

static void	handle_sigint(int sig)
{
	(void)sig;
	write(1, "\n", 1);
	rl_on_new_line();//reset cursor
	//rl_replace_line("", 0);//clear input
	rl_redisplay();//redraw prompt
}

void	setup_signals_interactive(void)
{
	signal(SIGINT, handle_sigint);
	signal(SIGQUIT, SIG_IGN);//Ignore the SIGQUIT signal, which is typically generated by pressing Ctrl + \, to prevent the shell from quitting when the user tries to quit the process.
	signal(SIGPIPE, SIG_IGN);//Ignore broken pipe signal to prevent shell from crashing when pipe is broken
}

void	setup_signals_exec(void)
{
	signal(SIGINT, SIG_DFL);//Let the system handle the signal normally default behavior, which typically terminates the process.
	signal(SIGQUIT, SIG_DFL);// example ctrl + c to stop the process and ctrl + \ to quit the process and dump core
	signal(SIGPIPE, SIG_IGN);//Ignore broken pipe signal to prevent shell from crashing when pipe is broken
}